[package]
name = "raw-parts"
version = "2.2.2"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
license = "MIT"
edition = "2021"
rust-version = "1.76.0"
readme = "README.md"
repository = "https://github.com/artichoke/raw-parts"
documentation = "https://docs.rs/raw-parts"
homepage = "https://github.com/artichoke/raw-parts"
description = """
Ergonomic wrapper around `Vec::from_raw_parts` and `Vec::into_raw_parts`.
"""
keywords = ["ffi", "no_std", "unsafe", "vec", "vector"]
categories = ["no-std", "rust-patterns"]
include = ["/src/**/*", "/tests/**/*", "/LICENSE", "/README.md"]

[dependencies]

[dev-dependencies]
# a no_std hasher for tests of `impl Hash for RawParts`
fnv = { version = "1.0.6", default-features = false }

[package.metadata.docs.rs]
# This sets the default target to `x86_64-unknown-linux-gnu` and only builds
# that target. `raw-parts` has the same API and code on all targets.
default-target = "x86_64-unknown-linux-gnu"
targets = []
rustdoc-args = ["--cfg", "docsrs"]
